---
title: "Sensitivity analysis"
output: html_notebook
---

Here I present the sensitivity of the model to alternate data sets, each corresponding to a specific interpretation of the phylogenetic data or model parameters.

I compiled 12 alternate data sets from the same spider phylogenies. All data sets and the files needed to produce them are included as data objects on this `R` package. The following table describes the differences between each data set.

## Scenario descriptions
|Scenario|Island Age|Favour cladogenesis|Favour MaxAge|
|:------:|:--------:|:-----------------:|:-----------:|
| y_c_max|   1.2My  |        Yes        |     Yes     |
| y_c_min|   1.2My  |        Yes        |     MinAge  |
| y_c_no |   1.2My  |        Yes        |     Never   |
| o_c_max|   2.4My  |        Yes        |     Yes     |
| o_c_min|   2.4My  |        Yes        |     MinAge  |
| o_c_no |   2.4My  |        Yes        |     Never   |
| y_m_max|   1.2My  |        No         |     Yes     |
| y_m_min|   1.2My  |        No         |     MinAge  |
| y_m_no |   1.2My  |        No         |     Never   |
| o_m_max|   2.4My  |        No         |     Yes     |
| o_m_min|   2.4My  |        No         |     MinAge  |
| o_m_no |   2.4My  |        No         |     Never   |

For 2.4 My old islands some instances of species are not tagged as missing (which they would be, if the island age were 1.2 My) because those branching times can be included. As an example compare the Pagiopalus_atomarius_Pagiopalus_sp clade between scenarios y_c_max and y_m_max.

MinAge favouring in the MaxAge column implies that MaxAgeMinAges are used when a min age is available and the precise colonisation time is available too. Not favouring MaxAge means MinAges only used **iff** the precise colonisation age is unknown and a min age is available. These are the "\_no" scenarios, which are arguable the most realistic ones from an empirical point of view.

## Model fitting

Seven different DAISIE models were fit to each of the data sets. Only constant rate models were used for these analyses, and no 

## Sensitivity

After having fit a collection of DAISIE models 

```{r Sensitivity, echo=TRUE}
age_names <- c(
  "age_c_max",
  "age_m_max",
  "age_c_min",
  "age_m_min",
  "age_c_no",
  "age_m_no"
)
age_comparisons <- list(
  "age_c_max" = c("y_c_max", "o_c_max"),
  "age_m_max" = c("y_m_max", "o_m_max"),
  "age_c_min" = c("y_c_min", "o_c_min"),
  "age_m_min" = c("y_m_min", "o_m_min"),
  "age_c_no" = c("y_c_min", "o_c_no"),
  "age_m_no" = c("y_m_min", "o_m_no")
)
age_sens <- list()
for (i in seq_along(age_comparisons)) {
  age_sens[[i]] <- DAISIEutils::sensitivity(
    age_comparisons[[i]], full_output = FALSE
  )
}
names(age_sens) <- age_names
age_sens
rate_names <- c(
  "rate_y_max",
  "rate_y_min",
  "rate_y_no",
  "rate_o_max",
  "rate_o_min",
  "rate_o_no"
)
rate_comparisons <- list(
  "rate_y_max" = c("y_c_max", "y_m_max"),
  "rate_y_min" = c("y_c_min", "y_m_min"),
  "rate_y_no" = c("y_c_no", "y_m_no"),
  "rate_o_max" = c("o_c_max", "o_m_max"),
  "rate_o_min" = c("o_c_min", "o_m_min"),
  "rate_o_no" = c("o_c_no", "o_m_no")
)
rate_sens <- list()
for (i in seq_along(rate_comparisons)) {
  rate_sens[[i]] <- DAISIEutils::sensitivity(
    rate_comparisons[[i]], full_output = FALSE
  )
}
names(rate_sens) <- rate_names
rate_input_rank <- lapply(rate_sens, "[[", 1)
knitr::kable(
  data.frame(
    rate_input_rank
  )
)
rate_model_rank <- lapply(rate_sens, "[[", 2)
knitr::kable(
  data.frame(
    rate_model_rank
  )
)
```


