#' DAISIE datatable of spiders on Hawaii (Big Island) - 1.1.1
#'
#' A dataset containing the colonization and branching times of spiders on Big
#' Island. This format can be passed to [DAISIE::DAISIE_dataprep()]. Endemicity
#' status refers strictly to Big Island endemics, and not endemics to the
#' Hawaiian archipelago in general. This dataset favours cladogenesis and
#' assumes MaxAge for most clades. Island age is set to 1.2My.
#'
#' @format A tibble with 33 rows and 5 variables:
#' \describe{
#'   \item{Clade_name}{character vector with name of each lineage}
#'   \item{Status}{character vector with endemicity status. Can be
#'   `"Endemic_MaxAge"`, `"NonEndemic_MaxAge"`, `"Endemic_MaxAgeMinAge"` or
#'   `"NonEndemic_MaxAgeMinAge"`}
#'   \item{Missing_species}{numeric with the number of known species that are
#'   missing in the phylogeny}
#'   \item{Branching_times}{ordered numeric vector with colonisation and
#'   branching times of each lineage. Can also contain `"MinAges"` when these
#'   are available}
#' }
#' @source Jairo Patiño and Rosemary Gilliespie. Full reference list to be
#'   filled in later.
#' @references
#' GARB, J.E. and GILLESPIE, R.G. (2009), Diversity despite dispersal:
#' colonization history and phylogeography of Hawaiian crab spiders inferred
#' from multilocus genetic data. Molecular Ecology, 18: 1746-1764.
#' <https://doi.org/10.1111/j.1365-294X.2009.04125.x>
"spider_scenario_1_1_1_datatable"

#' DAISIE datalist of spiders on Hawaii (Big Island) - 1.1.1
#'
#' A DAISIE datalist as required by [DAISIE::DAISIE_ML()]. Generated by running
#' [DAISIE::DAISIE_dataprep()] on [spider_scenario_1_1_1_datatable]. This
#' dataset favours cladogenesis and assumes MaxAge for most clades.
#' Island age is set to 1.2My.
#'
#' @format A list with 34 elements. The first one contains the `$island_age`,
#'   a numeric with the island age in Ma, and `$not_present`, a numeric with the
#'   number of known species on the archipelago not present on Big Island.
#'
#'   Each subsequent element of the list is comprised of 5 elements:
#' \describe{
#'   \item{$colonist_name}{character vector with name of each lineage.}
#'   \item{$branching_times}{A decreasingly sorted numeric vector. The first
#'   element is always the island age. Subsequent elements are either the
#'   speciation times or information regarding the minimum age at which the
#'   lineage could have colonised the archipelago.}
#'   \item{$stac}{A numeric integer from 1 to 9. Defines the status of the
#'   colonist, which has implications for the maximum likelihood inference.
#'   See [DAISIE::DAISIE_dataprep] for more details.}
#'   \item{$mising_species}{A numeric with the known number of missing species
#'   that are not present in the phylogeny, or cannot otherwise be assigned
#'   a branching time.}
#'   \item{$type1or2}{A numeric defining if the clade is of type 1 or 2, for 2
#'   type analyses. Always set to 1 in this dataset.}
#'
#' }
#' @source Jairo Patiño and Rosemary Gilliespie. Full reference list to be
#'   filled in later.
#' @references
#' GARB, J.E. and GILLESPIE, R.G. (2009), Diversity despite dispersal:
#' colonization history and phylogeography of Hawaiian crab spiders inferred
#' from multilocus genetic data. Molecular Ecology, 18: 1746-1764.
#' <https://doi.org/10.1111/j.1365-294X.2009.04125.x>
"spider_scenario_1_1_1_datalist"



#' DAISIE datatable of spiders on Hawaii (Big Island) - 1.1.2
#'
#' A dataset containing the colonization and branching times of spiders on Big
#' Island. This format can be passed to [DAISIE::DAISIE_dataprep()]. Endemicity
#' status refers strictly to Big Island endemics, and not endemics to the
#' Hawaiian archipelago in general. This dataset favours cladogenesis and does
#' not assume MaxAge for most clades. Island age is set to 1.2My.
#'
#' @format A tibble with 33 rows and 5 variables:
#' \describe{
#'   \item{Clade_name}{character vector with name of each lineage}
#'   \item{Status}{character vector with endemicity status. Can be
#'   `"Endemic_MaxAge"`, `"NonEndemic_MaxAge"`, `"Endemic_MaxAgeMinAge"` or
#'   `"NonEndemic_MaxAgeMinAge"`}
#'   \item{Missing_species}{numeric with the number of known species that are
#'   missing in the phylogeny}
#'   \item{Branching_times}{ordered numeric vector with colonisation and
#'   branching times of each lineage. Can also contain `"MinAges"` when these
#'   are available}
#' }
#' @source Jairo Patiño and Rosemary Gilliespie. Full reference list to be
#'   filled in later.
#' @references
#' GARB, J.E. and GILLESPIE, R.G. (2009), Diversity despite dispersal:
#' colonization history and phylogeography of Hawaiian crab spiders inferred
#' from multilocus genetic data. Molecular Ecology, 18: 1746-1764.
#' <https://doi.org/10.1111/j.1365-294X.2009.04125.x>
"spider_scenario_1_1_2_datatable"

#' DAISIE datalist of spiders on Hawaii (Big Island) - 1.1.2
#'
#' A DAISIE datalist as required by [DAISIE::DAISIE_ML()]. Generated by running
#' [DAISIE::DAISIE_dataprep()] on [spider_scenario_1_1_2_datatable]. This
#' dataset favours cladogenesis and does not assume MaxAge for most clades.
#' Island age is set to 1.2My.
#'
#' @format A list with 34 elements. The first one contains the `$island_age`,
#'   a numeric with the island age in Ma, and `$not_present`, a numeric with the
#'   number of known species on the archipelago not present on Big Island.
#'
#'   Each subsequent element of the list is comprised of 5 elements:
#' \describe{
#'   \item{$colonist_name}{character vector with name of each lineage.}
#'   \item{$branching_times}{A decreasingly sorted numeric vector. The first
#'   element is always the island age. Subsequent elements are either the
#'   speciation times or information regarding the minimum age at which the
#'   lineage could have colonised the archipelago.}
#'   \item{$stac}{A numeric integer from 1 to 9. Defines the status of the
#'   colonist, which has implications for the maximum likelihood inference.
#'   See [DAISIE::DAISIE_dataprep] for more details.}
#'   \item{$mising_species}{A numeric with the known number of missing species
#'   that are not present in the phylogeny, or cannot otherwise be assigned
#'   a branching time.}
#'   \item{$type1or2}{A numeric defining if the clade is of type 1 or 2, for 2
#'   type analyses. Always set to 1 in this dataset.}
#'
#' }
#' @source Jairo Patiño and Rosemary Gilliespie. Full reference list to be
#'   filled in later.
#' @references
#' GARB, J.E. and GILLESPIE, R.G. (2009), Diversity despite dispersal:
#' colonization history and phylogeography of Hawaiian crab spiders inferred
#' from multilocus genetic data. Molecular Ecology, 18: 1746-1764.
#' <https://doi.org/10.1111/j.1365-294X.2009.04125.x>
"spider_scenario_1_1_2_datalist"



#' DAISIE datatable of spiders on Hawaii (Big Island) - 1.2.1
#'
#' A dataset containing the colonization and branching times of spiders on Big
#' Island. This format can be passed to [DAISIE::DAISIE_dataprep()]. Endemicity
#' status refers strictly to Big Island endemics, and not endemics to the
#' Hawaiian archipelago in general. This dataset favours cladogenesis and does
#' not assume MaxAge for most clades. Island age is set to 2.4My.
#'
#' @format A tibble with 33 rows and 5 variables:
#' \describe{
#'   \item{Clade_name}{character vector with name of each lineage}
#'   \item{Status}{character vector with endemicity status. Can be
#'   `"Endemic_MaxAge"`, `"NonEndemic_MaxAge"`, `"Endemic_MaxAgeMinAge"` or
#'   `"NonEndemic_MaxAgeMinAge"`}
#'   \item{Missing_species}{numeric with the number of known species that are
#'   missing in the phylogeny}
#'   \item{Branching_times}{ordered numeric vector with colonisation and
#'   branching times of each lineage. Can also contain `"MinAges"` when these
#'   are available}
#' }
#' @source Jairo Patiño and Rosemary Gilliespie. Full reference list to be
#'   filled in later.
#' @references
#' GARB, J.E. and GILLESPIE, R.G. (2009), Diversity despite dispersal:
#' colonization history and phylogeography of Hawaiian crab spiders inferred
#' from multilocus genetic data. Molecular Ecology, 18: 1746-1764.
#' <https://doi.org/10.1111/j.1365-294X.2009.04125.x>
"spider_scenario_1_2_1_datatable"

#' DAISIE datalist of spiders on Hawaii (Big Island) - 1.2.1
#'
#' A DAISIE datalist as required by [DAISIE::DAISIE_ML()]. Generated by running
#' [DAISIE::DAISIE_dataprep()] on [spider_scenario_1_1_2_datatable]. This
#' dataset favours cladogenesis and does not assume MaxAge for most clades.
#' Island age is set to 2.4My.
#'
#' @format A list with 34 elements. The first one contains the `$island_age`,
#'   a numeric with the island age in Ma, and `$not_present`, a numeric with the
#'   number of known species on the archipelago not present on Big Island.
#'
#'   Each subsequent element of the list is comprised of 5 elements:
#' \describe{
#'   \item{$colonist_name}{character vector with name of each lineage.}
#'   \item{$branching_times}{A decreasingly sorted numeric vector. The first
#'   element is always the island age. Subsequent elements are either the
#'   speciation times or information regarding the minimum age at which the
#'   lineage could have colonised the archipelago.}
#'   \item{$stac}{A numeric integer from 1 to 9. Defines the status of the
#'   colonist, which has implications for the maximum likelihood inference.
#'   See [DAISIE::DAISIE_dataprep] for more details.}
#'   \item{$mising_species}{A numeric with the known number of missing species
#'   that are not present in the phylogeny, or cannot otherwise be assigned
#'   a branching time.}
#'   \item{$type1or2}{A numeric defining if the clade is of type 1 or 2, for 2
#'   type analyses. Always set to 1 in this dataset.}
#'
#' }
#' @source Jairo Patiño and Rosemary Gilliespie. Full reference list to be
#'   filled in later.
#' @references
#' GARB, J.E. and GILLESPIE, R.G. (2009), Diversity despite dispersal:
#' colonization history and phylogeography of Hawaiian crab spiders inferred
#' from multilocus genetic data. Molecular Ecology, 18: 1746-1764.
#' <https://doi.org/10.1111/j.1365-294X.2009.04125.x>
"spider_scenario_1_2_1_datalist"
