#' Default parameter documentation
#'
#' @param island_replicates List with DAISIE simulation output as generated by
#'   functions such as `DAISIE::DAISIE_sim_constant_rate()`.
#' @param plotting_table A `data.frame` as returned by
#'   `prepare_results_to_plot()`. It contains the full results of the package
#'   estimate runs together with necessary columns for data partitioning. Has 14
#'   columns, the first 10 of which are as returned by
#'   `DAISIEutils::sensitivity()` and the remaining four contain the
#'   integration, island age, cladogenesis/migration grouping and treatment of
#'   uncertainty grouping. All these are made up as factors to allow easy
#'   plotting.
#' @param parameter_names Vector with names of parameters using the codes
#'   usually found on `DAISIE` and as returned by `get_parameter_names()` by
#'   default. Can be of length 1 to 5, allows for:
#'   * `"lac"`
#'   * `"mu"`
#'   * `"K"`
#'   * `"gam"`
#'   * `"laa"`
#' @param partition_by A string indicating what the x-axis should be
#'   partitioned by. Options are `island_age` for partitioning by assumed island
#'   age, `stac` for partitioning by the treatment of uncertainty chosen, and
#'   `c_m` for partitioning by cladogenesis/migration favouring strategy.
#' @param colour_by A string indicating what data partitioning should be used
#'   for colours. Options are `island_age` for partitioning by assumed island
#'   age, `stac` for partitioning by the treatment of uncertainty chosen, and
#'   `c_m` for partitioning by cladogenesis/migration favouring strategy.
#' @param shape_by  A string indicating what data partitioning should be used
#'   for shapes. Options are `island_age` for partitioning by assumed island
#'   age, `stac` for partitioning by the treatment of uncertainty chosen, and
#'   `c_m` for partitioning by cladogenesis/migration favouring strategy.
#' @param sens A data frame consisting of the output of `DAISIE::sensitivity()`,
#'   which can include several scenarios.
#' @param parameter_name A string with the code name of 1 parameter. Possible
#'   names are returned by `get_parameter_names()` (although only 1 is
#'   accepted).
#' @param raw_results A data frame with the model results as returned by
#'   `make_res_df()`.
#' @param plot_to_save A ggplot which will be saved to disk.
#' @param type_size A string determining whether the figure should take full
#'   size in a page: `"full_size"` or only half: `"half_size"`
#' @param res A data frame with each row corresponding to the best of 10 model
#'   fits with a different set of randomly sampled starting parameters.
#' @param file_name A string with the name of a file.
#' @param partition_name A string corresponding to the internal code for
#'   partition names. Can be `"island_age"` for "Assumued island age (Ma)",
#'   `"c_m"` for "Uncertainty in number of colonisations", or `"stac"` for
#'   "Uncertainty in colonisation time"
#' @keywords internal
#' @return Nothing
#' @author Pedro Santos Neves
default_params_doc <- function(island_replicates,
                               plotting_table,
                               parameter_names,
                               partition_by,
                               colour_by,
                               shape_by,
                               sens,
                               parameter_name,
                               raw_results,
                               plot_to_save,
                               file_name,
                               type_size,
                               res,
                               partition_name) {

 # Intentionally empty
}
