#' Default parameter documentation
#'
#' @param island_replicates List with DAISIE simulation output as generated by
#'   functions such as `DAISIE::DAISIE_sim_constant_rate()`.
#'
#' @keywords internal
#' @return Nothing
#' @author Pedro Santos Neves
default_params_doc <- function(island_replicates) {

}
